sudo: required

service: docker

language: ruby
rvm:
  - 2.4.3

env:
  matrix:
    - INSTANCE=server-ubuntu-1604
    - INSTANCE=server-ubuntu-1804

# before_install:
# - mkdir ~/chef
# - openssl aes-256-cbc -K $encrypted_02ba4c0f2d2e_key -iv $encrypted_02ba4c0f2d2e_iv -in .travis/majormoses.pem.enc -out .travis/majormoses.pem -d

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

install: bundle --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle

script:
  - INSTANCE=$INSTANCE make travis

# when we are unblocked by: https://github.com/travis-ci/dpl/issues/841
# deploy:
#   edge: true
#   provider: chef-supermarket
#   user_id: majormoses
#   client-key: .travis/majormoses.pem
#   cookbook_category: Others
#   on:
#     tags: true
